# Jekyll

plugins:
  - jekyll-seo-tag

author:
  name: Christian Emmer

# Theme-specific
# @link https://pages.github.com/themes/
# @link https://github.com/topics/jekyll-theme
# @link https://github.com/just-the-docs/just-the-docs

remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3
