# Jekyll

plugins:
  - jekyll-seo-tag

author:
  name: Christian Emmer

# Theme-specific
# @link https://pages.github.com/themes/
# @link https://github.com/jekyll/minima

theme: minima

minima:
  skin: auto
  social_links:
   twitter: emmercm
   github: emmercm

header_pages:
  - docs/dats.md
  - docs/rom-filtering.md
  - docs/rom-headers.md
  - docs/rom-dumping.md
