# Jekyll

# Theme-specific
# @link https://github.com/jekyll/minima

theme: minima

minima:
  skin: auto
  twitter: emmercm
  github: emmercm

author:
  name: Christian Emmer

header_pages:
  - docs/dats.md
  - docs/rom-filtering.md
  - docs/rom-headers.md
  - docs/rom-dumping.md
